sonar.projectKey=JorkLucas03_StudyFlow
sonar.organization=jorklucas03
sonar.host.url=https://sonarcloud.io
sonar.projectName=StudyFlow
sonar.projectVersion=1.0.0

sonar.sourceEncoding=UTF-8
sonar.sources=src,backend/app
sonar.tests=tests,backend/tests

sonar.exclusions=node_modules/**,dist/**,test-results/**,.pytest_cache/**,backend/.pytest_cache/**,backend/.venv/**,backend/**/__pycache__/**,**/*.db,**/*.zip
sonar.test.inclusions=tests/**/*.js,backend/tests/**/*.py
sonar.coverage.exclusions=src/**,tests/**,backend/tests/**
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.12
